site_name: Ader's notebook
site_url: https://ader817.github.io/notebook
repo_name: Ader817/notebook
repo_url: https://github.com/Ader817/notebook/
edit_uri: tree/master/docs
site_description: Ader的笔记本
copyright: Copyright &copy; 2022-2024 <a href="https://github.com/Ader817" target="_blank" rel="noopener">Ader817</a>

theme: 
  name: 'material'
  language: 'zh'
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
  font: false
  palette:
    - scheme: default

nav:
  - Home:
    - home/index.md
  - Computer Science:
    - cs/index.md
    - "概率论与数理统计":
      - 简介: cs/pas/index.md
      - chapter1: cs/pas/ch1.md
  - Writeups:
    - writeups/index.md
    - "2024":
      - BaseCTF 2024: writeups/basectf/basectf2024.md

markdown_extensions:
  - toc:
      permalink: true # link for each title
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}} # enable Unicode link
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      # smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  # - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - mdx_math
