site_name: Ader's notebook
site_author: Ader
site_url: https://ader817.github.io/notebook
site_description: Ader's notebook

repo_name: Ader817/notebook
repo_url: https://github.com/Ader817/notebook/
use_directory_urls: false

copyright: Copyright &copy; 2024-2025 <a href="https://github.com/Ader817" target="_blank" rel="noopener">Ader817</a>

theme: 
  name: material
  custom_dir: overrides
  language: zh
  favicon: assets/images/favicon.ico
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.annotate
    - header.autohide
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    - navigation.prune
    - search.share
    - search.suggest
    - search.highlight
  font:
    text: JetBrains Mono, LXGW WenKai Screen GB Screen 
    code: JetBrains Mono, Consolas
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换至夜间模式

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent:  teal
      toggle:
        icon: material/brightness-4
        name: 切换至日间模式
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
    logo: octicons/paper-airplane-16

plugins:
  - search
  - heti:
      disable_serve: true
  - statistics: # 需要在 markdown_extensions 里面加一句 md_in_html 才能显示 icon
      #page_template: "assets/stylesheets/statistics.html"
      page_check_metadata: counter
      words_per_minute: 150
  - awesome-pages # 自动根据文件大标题生成侧边目录标题

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      title: 目录
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}} # enable Unicode link
  - md_in_html

extra_css:
  #- https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  #- assets/stylesheets/counter.css
  #- https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  - assets/stylesheets/custom.css
  - https://unpkg.com/katex@0/dist/katex.min.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,100..800;1,100..800&display=swap
  
extra_javascript:
  # - assets/javascripts/mathjax.js
  # - https://cdn.jsdelivr.net/gh/Wcowin/Wcowin.github.io@main/docs/javascripts/extra.js  # extra的cdn
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/javascripts/katex.js 
  - assets/javascripts/toc.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js


nav:
  - Home:
    - index.md

  - Algorithm:
    - algorithm/index.md
    - "高级数据结构与算法分析":
      - algorithm/ads/index.md
      - algorithm/ads/ch0.md
      - algorithm/ads/ch1.md
      - algorithm/ads/ch2.md
      - algorithm/ads/ch3.md
      - algorithm/ads/ch4.md
      - algorithm/ads/ch5.md
      - algorithm/ads/ch6.md
      - algorithm/ads/ch7.md
      - algorithm/ads/ch8.md
      - algorithm/ads/ch9.md
      - algorithm/ads/ch10.md
      - algorithm/ads/ch11.md
      - algorithm/ads/problem.md

  - Software:
    - software/index.md
    - "图像信息处理":
      - software/dip/index.md
      - software/dip/ch1.md
      - software/dip/ch2.md
      - software/dip/ch3.md
      - software/dip/ch4.md
      - software/dip/ch5.md
      - software/dip/ch6.md

  - System:
    - system/index.md
    - "计算机组成原理":
      - system/co/index.md
      - system/co/ch1.md
      - system/co/ch2.md
      - system/co/ch3.md
      - system/co/ch4.md

  - Math:
    - math/index.md
    - "概率论与数理统计":
      - math/pas/index.md
      - math/pas/ch1.md
      - math/pas/ch2.md
      - math/pas/ch3.md
      - math/pas/ch4.md
      - math/pas/ch5.md
      - math/pas/ch6.md
      - math/pas/ch7.md
      - math/pas/ch8.md

  - Writeups:
    - writeups/index.md
    - "2024":
      - BaseCTF 2024: writeups/basectf/basectf2024.md