site_name: Ader's notebook
site_url: https://ader817.github.io/notebook
repo_name: Ader817/notebook
repo_url: https://github.com/Ader817/notebook/
edit_uri: tree/master/docs
site_description: Ader的笔记本
copyright: Copyright &copy; 2022-2024 <a href="https://github.com/Ader817" target="_blank" rel="noopener">Ader817</a>

theme: 
  name: 'material'
  language: 'zh'
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
  font: false
  palette:
    - scheme: default

nav:
  - Home:
    - home/index.md
  - Computer Science:
    - cs/index.md
    - "概率论与数理统计":
      - 简介: cs/pas/index.md
      - Chapter1: cs/pas/ch1.md
      - Chapter2: cs/pas/ch2.md
    - "高级数据结构与算法分析":
      - Chapter 2 | Red Black Tree & B+ Tree: cs/ads/ch2.md
      - Chapter 3 | Inverted File Index: cs/ads/ch3.md
      - Chapter 4 | Leftist Heap & Skew Heap: cs/ads/ch4.md
      - Chapter 5 | Binomial Queue & Fibonacci Heap: cs/ads/ch5.md
      - Chapter 6 | Search and Backtracing: cs/ads/ch6.md
    - "图像信息处理":
      - Chapter 1 | 成像与图像的基本属性: cs/dip/ch1.md
      - Chapter 2 | 二值图像与形态学: cs/dip/ch2.md
      
  - Writeups:
    - writeups/index.md
    - "2024":
      - BaseCTF 2024: writeups/basectf/basectf2024.md

markdown_extensions:
  - toc:
      permalink: true # link for each title
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}} # enable Unicode link
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      # smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  # - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/gh/TRHX/CDN-for-itrhx.com@3.0.8/js/maodian.js